openapi: 3.0.0
info:
  title: My GitHub App API
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /webhook:
    post:
      summary: Webhook for branch merge event
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookPayload'
      responses:
        '200':
          description: Webhook successfully processed
components:
  schemas:
    WebhookPayload:
      type: object
      properties:
        ref:
          type: string
        before:
          type: string
        after:
          type: string
        repository:
          type: object
          properties:
            full_name:
              type: string
            html_url:
              type: string
        pusher:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        commits:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              message:
                type: string
              timestamp:
                type: string
              url:
                type: string
              author:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
securitySchemes:
  BearerAuth:
    type: apiKey
    in: header
    name: Authorization
    description: Bearer token obtained from GitHub webhook secret
